# docker-compose.yml
services:
  review-analyzer:
    build: .
    volumes:
      - .:/app  # 전체 프로젝트 디렉토리를 마운트하여 파일 접근성 보장
    environment:
      - PYTHONUNBUFFERED=1  # 파이썬 출력 버퍼링 비활성화
    stdin_open: true  # docker run -i 와 동일
    tty: true        # docker run -t 와 동일